version: '3.8'

services:
  hoehetis:
    build: .
    volumes:
      - type: bind
        source: data
        target: /app/data
      - type: bind
        source: public
        target: /app/public
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

