version: '3.8'

services:
  hoehetis:
    build: .
    volumes:
      - type: volume
        source: data
        target: /app/data
      - type: volume
        source: public
        target: /app/public
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

volumes:
  data:

  public: